In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel(r'C:\Jupyter_notebook\PandasNumPyCourse\data\Customer Call List.xlsx')
df.info() # checking the data types of the columns and if there are any missing values  
# проверка типов данных в колонках и наличия пропущенных значений

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

In [4]:
df.head(10) # checking the first 10 rows of the data frame to understand the structure of the data
# проверка первых 10 строк датафрейма для понимания структуры данных

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True

In [5]:
df = df.drop_duplicates() # removing duplicate rows from the data frame
# удаление дублирующихся строк из датафрейма

In [6]:
df['Last_Name'] = df['Last_Name'].str.strip("123._/") # removing unwanted characters from the Last_Name column
# удаление нежелательных символов из колонки Last_Name

In [7]:
# Оставляем только цифры и буквы (убираем спецсимволы)
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '', regex=True)
# удаление всех символов, кроме букв и цифр, из колонки Phone_Number

In [8]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True

In [9]:
df.info() # checking the data types of the columns and if there are any missing values after cleaning the data
# проверка типов данных в колонках и наличия пропущенных значений после очистки данных

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         20 non-null     int64
 1   First_Name         20 non-null     object
 2   Last_Name          19 non-null     object
 3   Phone_Number       15 non-null     object
 4   Address            20 non-null     object
 5   Paying Customer    20 non-null     object
 6   Do_Not_Contact     16 non-null     object
 7   Not_Useful_Column  20 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

In [ ]:
df = df.drop(columns=["Not_Useful_Column"]) 
# dropping the Not_Useful_Column from the data frame
# удаление колонки Not_Useful_Column из датафрейма

In [ ]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
# converting the Phone_Number column to string data type
# преобразование колонки Phone_Number в строковый тип данных

In [12]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
# formatting the Phone_Number column to the format XXX-XXX-XXXX
# форматирование колонки Phone_Number в формат XXX-XXX-XXXX

In [14]:
df.head(10) # checking the first 10 rows of the cleaned data frame to see the changes made to the data
# проверка первых 10 строк очищенного датафрейма, чтобы увидеть изменения, внесенные в данные

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No